"""
scripts/webapp.py
=================
The Apex Quant web app — a friendly, plain-language page anyone can understand,
with all the technical depth kept one click away.

Designed for a non-expert: a calm light theme, a hero that says what it is in one
line, live numbers each explained in plain words, a "how it works in 3 steps"
explainer, six capability tiles, a "Common questions" section, and a plain-English
glossary. Every technical detail is preserved behind clearly-labelled
"for developers" expanders (progressive disclosure) — the full module list for
each capability is generated by introspecting each module's own docstring via
``ast`` so the app can never drift out of sync with the code.

Stdlib only (``ast`` + ``http.server``) — consistent with the $0-infra principle.
Pages is static-only, so:

  python -m scripts.webapp --build site/index.html   # render the static site (CI / Pages)
  python -m scripts.webapp                           # serve locally on http://127.0.0.1:8788
  python -m scripts.webapp --port 9000

Read-only: it never touches the broker or mutates the state DB.
"""

from __future__ import annotations

import argparse
import ast
import html
import os
import sys
from decimal import Decimal
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

from scripts.dashboard import _SHIPPED, _badge_class, _money, _recent_progress
from scripts.status import DEFAULT_STATE_PATH, GATE_DAYS, _read_state

_REPO = Path(__file__).resolve().parent.parent
_GH = "https://github.com/Dukotah/apex-quant/blob/main"

# Self-contained, friendly LIGHT theme (decoupled from the dev dashboard's dark CSS).
_THEME = """
:root{--bg:#f5f7fb;--card:#ffffff;--ink:#16202e;--muted:#5b6b80;--line:#e4e9f0;
--accent:#2563eb;--soft:#eef3fb;--grn:#15803d;--yel:#b45309;--red:#dc2626;--cyn:#2563eb}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);
font:16px/1.65 ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif}
.wrap{max-width:1000px;margin:0 auto;padding:22px 20px 70px}
a{color:var(--accent);text-decoration:none}a:hover{text-decoration:underline}
h1{font-size:34px;line-height:1.12;margin:0 0 12px;letter-spacing:-.02em}
.hero{background:linear-gradient(160deg,#e9f1ff 0%,#f5f7fb 72%);border:1px solid var(--line);
border-radius:20px;padding:38px 30px;box-shadow:0 1px 3px rgba(16,32,46,.05)}
.hero .pitch{color:#33445a;font-size:18px;line-height:1.6;max-width:60ch;margin:0 0 20px}
.pill{display:inline-flex;align-items:center;gap:8px;font-size:14px;font-weight:600;padding:7px 15px;
border-radius:999px;border:1px solid #b7e0c4;color:var(--grn);background:#e9f7ef}
.pill.red{border-color:#f4c2c2;color:var(--red);background:#fdeaea}
.pill .dot{width:9px;height:9px;border-radius:50%;background:currentColor}
.tiles{display:grid;grid-template-columns:repeat(auto-fit,minmax(168px,1fr));gap:14px;margin-top:22px}
.tile{background:#fff;border:1px solid var(--line);border-radius:15px;padding:16px 18px;
box-shadow:0 1px 2px rgba(16,32,46,.04)}
.tile .k{color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.05em;font-weight:600}
.tile .v{font-size:27px;font-weight:800;margin:5px 0 2px;letter-spacing:-.01em;font-variant-numeric:tabular-nums}
.tile .cap{color:var(--muted);font-size:12.5px;line-height:1.4}
.readme{background:var(--soft);border:1px solid #d6e2f5;color:#33445a;border-radius:12px;
padding:13px 16px;margin:16px 0 4px;font-size:14.5px}
nav.top{display:flex;flex-wrap:wrap;gap:6px;margin:18px 0 30px;position:sticky;top:0;z-index:5;
background:#f5f7fbe6;backdrop-filter:blur(8px);padding:10px 0;border-bottom:1px solid var(--line)}
nav.top a{color:var(--muted);font-weight:600;font-size:14px;padding:7px 14px;border-radius:10px}
nav.top a:hover{background:#fff;color:var(--ink);text-decoration:none;box-shadow:0 1px 2px rgba(16,32,46,.06)}
section.blk{margin:0 0 46px;scroll-margin-top:72px}
section.blk>h2{font-size:23px;letter-spacing:-.02em;margin:0 0 8px}
.note{color:#44556b;font-size:16px;max-width:74ch;margin:0 0 20px;line-height:1.65}
.note b{color:var(--ink);font-weight:700}
.card{background:#fff;border:1px solid var(--line);border-radius:14px;padding:16px 18px;
box-shadow:0 1px 2px rgba(16,32,46,.04)}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:14px}
.grid.ship{grid-template-columns:repeat(auto-fit,minmax(280px,1fr))}
.steps{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:16px}
.step{background:#fff;border:1px solid var(--line);border-radius:16px;padding:22px;
box-shadow:0 1px 2px rgba(16,32,46,.04)}
.step .ic{font-size:32px}
.step .num{float:right;color:#fff;background:var(--accent);font-size:13px;font-weight:700;border-radius:999px;
width:26px;height:26px;display:inline-flex;align-items:center;justify-content:center}
.step h3{margin:12px 0 7px;font-size:18px}
.step p{margin:0;color:#44556b;font-size:15px}
.caps{display:grid;grid-template-columns:repeat(auto-fit,minmax(310px,1fr));gap:16px}
.cap{background:#fff;border:1px solid var(--line);border-radius:16px;padding:22px;
box-shadow:0 1px 2px rgba(16,32,46,.04)}
.cap .ic{font-size:30px}
.cap h3{margin:11px 0 6px;font-size:18px;display:flex;justify-content:space-between;align-items:center;gap:8px}
.cap .cnt{font-size:12px;font-weight:600;color:var(--accent);background:var(--soft);
border:1px solid #d6e2f5;border-radius:999px;padding:2px 11px;white-space:nowrap}
.cap>p{margin:0 0 14px;color:#44556b;font-size:15px}
details{border-top:1px solid var(--line);padding-top:12px}
details>summary{cursor:pointer;color:var(--accent);font-size:13.5px;font-weight:600;list-style:none}
details>summary::-webkit-details-marker{display:none}
details>summary:hover{text-decoration:underline}
details[open]>summary{margin-bottom:14px}
.faq details{border:1px solid var(--line);border-radius:13px;padding:15px 18px;margin-bottom:11px;background:#fff;
box-shadow:0 1px 2px rgba(16,32,46,.04)}
.faq summary{color:var(--ink);font-size:16.5px;font-weight:700}
.faq summary::after{content:" +";color:var(--muted);float:right}
.faq details[open] summary::after{content:" –"}
.faq p{margin:12px 0 0;color:#44556b;font-size:15.5px}
.gloss{display:grid;gap:10px}
.gterm{background:#fff;border:1px solid var(--line);border-radius:12px;padding:13px 16px}
.gterm b{color:var(--ink)}.gterm span{color:#44556b;display:block;margin-top:2px;font-size:15px}
.gates2{display:grid;gap:10px}
.gate2{display:flex;flex-wrap:wrap;gap:6px 16px;background:#fff;border:1px solid var(--line);
border-radius:13px;padding:15px 17px;box-shadow:0 1px 2px rgba(16,32,46,.04)}
.gate2 .g{color:var(--ink);font-weight:700;min-width:185px}
.gate2 .d{color:#44556b;font-size:15px;flex:1}
.phases{display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:16px}
.phase{background:#fff;border:1px solid var(--line);border-left:5px solid var(--muted);
border-radius:15px;padding:20px;box-shadow:0 1px 2px rgba(16,32,46,.04)}
.phase.ok{border-left-color:var(--grn)}.phase.work{border-left-color:var(--accent)}
.phase.behind{border-left-color:var(--red)}
.phase h3{margin:0 0 8px;font-size:14px;text-transform:uppercase;letter-spacing:.05em;font-weight:800}
.phase p{margin:0;color:#44556b;font-size:15px}
.scard{border-left:4px solid var(--line)}
.scard.ok{border-left-color:var(--grn)}.scard.work{border-left-color:var(--yel)}
.scard.behind{border-left-color:var(--red)}
.scard .h{display:flex;justify-content:space-between;align-items:baseline;gap:8px}
.scard h3{margin:0;font-size:15px}.scard p{margin:7px 0 0;color:#44556b;font-size:13.5px}
.badge{font-size:11.5px;font-weight:600;padding:2px 10px;border-radius:999px;border:1px solid var(--line);
color:var(--muted);background:#f1f4f9}
.badge.ok{color:var(--grn);background:#e9f7ef;border-color:#b7e0c4}
.badge.work{color:var(--yel);background:#fdf3e7;border-color:#f0d2a8}
.badge.behind{color:var(--red);background:#fdeaea;border-color:#f4c2c2}
.bar{display:flex;flex-wrap:wrap;gap:9px}
.chip{background:#fff;border:1px solid var(--line);border-radius:999px;padding:6px 13px;font-size:13.5px;color:var(--muted)}
.chip b{color:var(--ink);font-weight:700}
.chip.ok b{color:var(--grn)}.chip.red b{color:var(--red)}.chip.cyn b{color:var(--accent)}
.barwrap{background:#eef2f7;border:1px solid var(--line);border-radius:999px;height:14px;overflow:hidden;margin:4px 0 10px}
.barfill{height:100%;background:linear-gradient(90deg,#3b82f6,#2563eb)}
table{width:100%;border-collapse:collapse;font-variant-numeric:tabular-nums}
th{text-align:right;color:var(--muted);font-size:11.5px;text-transform:uppercase;letter-spacing:.04em;
padding:7px 10px;border-bottom:1px solid var(--line)}
th:first-child,td:first-child{text-align:left}
td{padding:8px 10px;border-top:1px solid var(--line);font-size:14px}
.pos{color:var(--grn)}.neg{color:var(--red)}
.sub{color:var(--muted)}
pre{margin:0;white-space:pre-wrap;font:12.5px/1.6 ui-monospace,Menlo,Consolas,monospace;color:#44556b}
.foot{color:var(--muted);font-size:13px;margin-top:34px;border-top:1px solid var(--line);padding-top:16px}
.runbox{display:flex;flex-wrap:wrap;gap:10px;align-items:center}
.runbox select{font:inherit;font-size:15px;padding:10px 12px;border:1px solid var(--line);border-radius:11px;
background:#fff;color:var(--ink);min-width:230px}
.btn{font:inherit;font-size:15px;font-weight:700;padding:10px 20px;border:0;border-radius:11px;cursor:pointer;
background:var(--accent);color:#fff;box-shadow:0 1px 2px rgba(16,32,46,.1)}
.btn:hover{background:#1d4ed8}.btn:disabled{opacity:.55;cursor:default}
#result{margin-top:16px}
.grade{display:inline-flex;align-items:center;gap:8px;font-size:15px;font-weight:800;padding:8px 16px;
border-radius:999px;border:1px solid var(--line)}
.grade.ok{color:var(--grn);background:#e9f7ef;border-color:#b7e0c4}
.grade.work{color:var(--yel);background:#fdf3e7;border-color:#f0d2a8}
.grade.behind{color:var(--red);background:#fdeaea;border-color:#f4c2c2}
.spin{display:inline-block;width:15px;height:15px;border:2px solid #c9d6e8;border-top-color:var(--accent);
border-radius:50%;animation:sp .8s linear infinite;vertical-align:-2px;margin-right:7px}
@keyframes sp{to{transform:rotate(360deg)}}
@media(max-width:640px){.wrap{padding:16px 14px 60px}h1{font-size:27px}.hero{padding:26px 20px}.hero .pitch{font-size:16px}}
"""

# Subsystems generated from the real module tree. (sid, title, [globs], lead)
SECTIONS: list[tuple[str, str, list[str], str]] = [
    ("strategies", "Strategies", ["apex/strategy/library/*.py"], ""),
    ("indicators", "Indicators", ["apex/strategy/indicators.py", "apex/strategy/ind_*.py"], ""),
    ("validation", "Validation", ["apex/validation/*.py"], ""),
    ("risk", "Risk", ["apex/risk/*.py"], ""),
    ("execution", "Execution", ["apex/execution/*.py"], ""),
    ("data", "Data", ["apex/data/*.py"], ""),
    ("analytics", "Analytics", ["apex/analytics/*.py"], ""),
    ("backtest", "Backtest", ["apex/backtest/*.py"], ""),
    ("core", "Core", ["apex/core/*.py"], ""),
    ("ops", "Ops", ["apex/ops/*.py", "scripts/*.py"], ""),
]

# Curated status overlay for strategies we have a verdict on; the rest render as
# tested research references.
_STRATEGY_STATUS: dict[str, str] = {
    "multi_asset_trend": "LIVE",
    "cross_asset_value": "CANDIDATE",
    "ts_momentum_blend": "ARCHIVED",
    "value_momentum": "research",
    "cross_sectional_momentum": "research",
    "short_term_reversal": "research",
    "bond_carry": "research",
    "breadth_momentum": "research",
    "credit_spread": "research",
    "turn_of_month": "research",
    "options_income": "gated",
    "long_short_momentum": "gated",
}

# Friendly capability tiles. (cap id, icon, title, plain description, [member sids])
_CAPS: list[tuple[str, str, str, str, list[str]]] = [
    (
        "strategies",
        "📈",
        "Strategies",
        "The trading playbooks. Each one watches the market and only ever suggests a trade — "
        "it can never place one itself, so a bad idea can't reach the broker.",
        ["strategies", "indicators"],
    ),
    (
        "safety",
        "🛡️",
        "Safety & risk",
        "One gatekeeper that can't be bypassed: it sizes every trade, insists on a safety "
        "exit, caps how much can be at stake, and stops everything if losses pile up.",
        ["risk", "execution"],
    ),
    (
        "validation",
        "🔬",
        "Testing & proof",
        "Before a strategy risks a cent it must survive a battery of tests built to expose "
        "luck, wishful thinking, and hidden trading costs.",
        ["validation", "backtest"],
    ),
    (
        "data",
        "🗄️",
        "Market data",
        "Clean, trustworthy prices — fetched, tidied, and sanity-checked before the system "
        "ever acts on them.",
        ["data"],
    ),
    (
        "analytics",
        "📊",
        "Analytics",
        "Plain-English performance reporting: how much it made or lost, its worst stretches, "
        "and what's driving the results.",
        ["analytics"],
    ),
    (
        "ops",
        "⚙️",
        "Operations",
        "The autopilot: it runs once a day on a free schedule, keeps a record of everything, "
        "watches itself, and pings you if anything looks off.",
        ["ops", "core"],
    ),
]

# How it works, in three plain steps. (icon, title, description)
_STEPS: list[tuple[str, str, str]] = [
    (
        "🔍",
        "Spot",
        "Once a day the strategies scan the markets and flag what's worth holding — as suggestions only.",
    ),
    (
        "🛡️",
        "Check",
        "The safety system reviews every suggestion: is it the right size? does it have an exit? is it within the limits? Anything unsafe becomes “no trade.”",
    ),
    (
        "✅",
        "Trade",
        "Approved trades go to the broker (pretend money for now) and every result is recorded, every day.",
    ),
]

# The Gauntlet in plain language. (label, plain-English meaning)
_GATES: list[tuple[str, str]] = [
    (
        "Gate 1 · Worth the risk",
        "Does it earn enough for the ups, downs, and worst-case loss it takes on?",
    ),
    ("Gate 2 · Not fooling ourselves", "Does it still work on data it was never tuned on?"),
    (
        "Gate 3 · Holds up over time",
        "Re-tested again and again on later, unseen periods — does it keep working?",
    ),
    (
        "Gate 4 · Real, not lucky",
        "Shuffle the trades thousands of times — is the edge genuine or one lucky run?",
    ),
    ("Gate 5 · Beats noise", "Scramble the price history — can it still beat pure randomness?"),
    ("Gate 6 · Survives costs", "Does it still win after doubling real-world trading costs?"),
    ("Gate 7 · Beats the market", "Does it out-earn simply buying and holding the S&P 500?"),
    (
        "Gate 8 · Honest scoring",
        "Discounts the score for how many ideas we tried (a soft warning).",
    ),
]

# Plain-language roadmap. (phase, colour class, text)
_ROADMAP: list[tuple[str, str, str]] = [
    (
        "Done",
        "ok",
        "Built the engine, the unbypassable safety system, and a working trend "
        "strategy. It's live on pretend money, and the go-live safety checks are complete.",
    ),
    (
        "Now",
        "work",
        "Finishing a 30-day practice run. When it passes, start with a small amount "
        "of real money — but first move the records off the public site.",
    ),
    (
        "Later",
        "muted",
        "Add a second, independent strategy and let the system split money between "
        "them; then explore more (options, other markets).",
    ),
]

# Common questions, in plain words. (question, answer)
_FAQ: list[tuple[str, str]] = [
    (
        "Is real money at risk right now?",
        "No. It's trading pretend (“paper”) money in a practice account. Nothing real is on the "
        "line until it passes its trial and you choose to fund it.",
    ),
    (
        "What is it actually doing?",
        "Once a day it looks at a handful of markets — US and foreign stocks, government bonds, "
        "gold and commodities — and holds the ones trending up while stepping aside from the ones "
        "trending down.",
    ),
    (
        "How do you know it works?",
        "Every strategy has to pass 8 tough tests before it's trusted with money — and even then "
        "it runs on pretend money for 30 days to prove the results hold up.",
    ),
    (
        "What stops it from doing something reckless?",
        "A separate safety system reviews every single trade and can veto it. A strategy can't "
        "place a trade by itself, every trade needs a built-in exit, and the whole system shuts "
        "off if losses get too large.",
    ),
    (
        "Could I lose money?",
        "Any trading carries risk. The safety limits are designed to trim losses early and stop "
        "well before anything drastic — but only ever fund money you could afford to lose.",
    ),
    (
        "Is this financial advice?",
        "No. It's a personal tool that runs one account. It isn't advice, and it doesn't manage "
        "anyone else's money.",
    ),
    (
        "What does it cost to run?",
        "About $0 — it runs entirely on free services: a free broker practice account, free "
        "scheduled runs, and a small built-in database.",
    ),
]

# Plain-English glossary. (term, definition)
_GLOSSARY: list[tuple[str, str]] = [
    ("Paper trading", "Practice trading with fake money — real prices, no real cash at stake."),
    ("Account value", "What the account is worth right now: cash plus whatever it's holding."),
    ("Drawdown", "How far down the account is from its best-ever value. Smaller is better."),
    ("Safety exit (stop-loss)", "An automatic “sell if it falls to here” attached to every trade."),
    ("Backtest", "Replaying years of history to see how a strategy would have done."),
    ("The Gauntlet", "Our set of 8 tests a strategy must pass before it's trusted with money."),
    ("Trend following", "Ride things that are going up; step aside when they turn down."),
]


# Strategies you can run from the local app, each wired to real data + benchmark
# in scripts/validate_real.py. (key, friendly label, validate_* function name).
_RUNNABLE: list[tuple[str, str, str]] = [
    ("smart7", "Multi-asset trend — the deployed strategy", "validate_multiasset_smart7"),
    ("multiasset", "Multi-asset trend (5 sleeves)", "validate_multiasset"),
    ("trend_bond", "Trend + bond", "validate_trend_bond"),
    ("spy_trend", "SPY trend filter", "validate_spy_trend"),
    ("dual_momentum", "Dual momentum", "validate_dual_momentum"),
    ("etf_rotation", "ETF sector rotation", "validate_etf_rotation"),
    ("rsi2", "RSI(2) mean reversion", "validate_rsi2"),
    ("rsi2_vol", "RSI(2), volatility-filtered", "validate_rsi2_vol"),
    ("value", "Cross-asset value", "validate_value"),
    ("value_singlenames", "Single-name value (large caps)", "validate_value_singlenames"),
]
_RUNNABLE_FN = {key: fn for key, _label, fn in _RUNNABLE}

# Client-side runner: calls the local /api/run endpoint and shows the graded result.
_RUN_JS = """
<script>
async function runGauntlet(){
  var b=document.getElementById('runbtn'), s=document.getElementById('strat'), r=document.getElementById('result');
  var label=s.options[s.selectedIndex].text; b.disabled=true;
  r.innerHTML='<div class="card"><span class="spin"></span>Running “'+label+'” through the Gauntlet on real market history… this can take up to a minute.</div>';
  try{
    var resp=await fetch('/api/run?strategy='+encodeURIComponent(s.value));
    var txt=await resp.text();
    r.innerHTML = resp.ok ? txt : '<div class="card">Could not finish:<pre>'+txt+'</pre></div>';
  }catch(e){ r.innerHTML='<div class="card">Could not run: '+e+'</div>'; }
  b.disabled=false;
}
</script>
"""


def run_strategy(key: str):
    """Run one wired strategy through the real-data Gauntlet. Returns (report, inputs).

    Lazy-imports scripts.validate_real so the heavy strategy/data stack only loads
    when something is actually run — never at page-render or import time.
    """
    fn_name = _RUNNABLE_FN.get(key)
    if fn_name is None:
        raise KeyError(f"unknown strategy {key!r}")
    import scripts.validate_real as vr

    return getattr(vr, fn_name)()


def _grade_class(grade: str) -> str:
    g = grade.upper()
    if g in ("A", "B"):
        return "ok"
    if g == "C":
        return "work"
    return "behind"


def _result_html(report, inputs) -> str:
    """Render a finished Gauntlet run: grade, per-gate results, and headline metrics."""
    gv = str(getattr(report.grade, "value", report.grade))
    rows = []
    for g in report.gates:
        sv = str(getattr(g.status, "value", g.status))
        scls = {"PASS": "ok", "WARN": "work", "FAIL": "behind"}.get(sv.upper(), "muted")
        rows.append(
            f"<tr><td>{html.escape(g.name)}</td>"
            f'<td><span class="badge {scls}">{html.escape(sv)}</span></td>'
            f"<td>{html.escape(str(g.detail))}</td></tr>"
        )
    table = (
        "<table><tr><th>Test</th><th>Result</th><th>Detail</th></tr>" + "".join(rows) + "</table>"
    )
    verdict = {
        "A": "Passed — a real, deployable edge.",
        "B": "Passed — a solid edge.",
        "C": "Marginal — proceed with caution.",
    }.get(gv.upper(), "Failed the Gauntlet — not a real edge (kept as a reference).")
    metrics = (
        f"{inputs.num_trades} trades · in-sample Sharpe {inputs.in_sample_sharpe:.2f} · "
        f"out-of-sample {inputs.out_of_sample_sharpe:.2f} · full {inputs.full_sharpe:.2f} · "
        f"after 2× costs {inputs.sharpe_at_2x_cost:.2f} · vs S&P {inputs.benchmark_sharpe:.2f} "
        f"(correlation {inputs.correlation_to_benchmark:.2f})"
    )
    return (
        f'<div class="card"><span class="grade {_grade_class(gv)}">Grade {html.escape(gv)}</span>'
        f'<p style="margin:13px 0 3px"><b>{html.escape(str(report.strategy_name))}</b> — '
        f"{html.escape(verdict)}</p>"
        f'<p class="sub" style="margin:0 0 14px;font-size:13.5px">{html.escape(metrics)}</p>'
        f"{table}</div>"
    )


def _runit_section(interactive: bool) -> str:
    """The 'Run a backtest' control panel (live locally; a disabled preview on Pages)."""
    opts = "".join(
        f'<option value="{html.escape(k)}">{html.escape(label)}</option>'
        for k, label, _fn in _RUNNABLE
    )
    if not interactive:
        body = (
            '<div class="card"><div class="runbox"><select disabled>'
            f'{opts}</select><button class="btn" disabled>Run the Gauntlet ▸</button></div>'
            '<p class="sub" style="margin-top:11px">▶ This runs live when you start the app on your '
            "own machine: <code>python -m scripts.webapp</code>, then open "
            '<a href="http://127.0.0.1:8788">127.0.0.1:8788</a>. (GitHub Pages can only show pages, '
            "not run code.)</p></div>"
        )
        return _blk(
            "run",
            "Run a backtest",
            "Pick a strategy and put it through the real-data Gauntlet — the same test that decides "
            "whether something is trusted with money.",
            body,
        )
    body = (
        '<div class="card"><div class="runbox">'
        f'<select id="strat">{opts}</select>'
        '<button class="btn" id="runbtn" onclick="runGauntlet()">Run the Gauntlet ▸</button>'
        '</div><p class="sub" style="margin-top:11px">Runs the chosen strategy through all 8 tests on '
        "real market history — takes a few seconds to a minute.</p>"
        '<div id="result"></div></div>' + _RUN_JS
    )
    return _blk(
        "run",
        "Run a backtest",
        "Pick a strategy and put it through the real-data Gauntlet — the same test that decides "
        "whether something is trusted with money.",
        body,
    )


# --------------------------------------------------------------- introspection


def _summary(path: Path) -> str:
    """First descriptive line of a module's docstring (no import, via ast)."""
    try:
        doc = ast.get_docstring(ast.parse(path.read_text(encoding="utf-8"))) or ""
    except (OSError, SyntaxError, ValueError):
        return ""
    out: list[str] = []
    for raw in doc.splitlines():
        ln = raw.strip()
        if not ln:
            if out:
                break
            continue
        if ln.endswith(".py") or (set(ln) <= set("=-~_")):  # skip path header + underline
            continue
        out.append(ln)
        if ln.endswith(".") or len(" ".join(out)) > 170:
            break
    return " ".join(out)[:220]


def _modules(globs: list[str]) -> list[tuple[str, str, str]]:
    """(repo-relative path, stem, summary) for every non-dunder module in `globs`."""
    seen: set[Path] = set()
    items: list[tuple[str, str, str]] = []
    for g in globs:
        for p in sorted(_REPO.glob(g)):
            if p.name.startswith("__") or p in seen:
                continue
            seen.add(p)
            items.append((p.relative_to(_REPO).as_posix(), p.stem, _summary(p)))
    return items


# ------------------------------------------------------------------- rendering


def _module_cards(items: list[tuple[str, str, str]], status: dict[str, str] | None = None) -> str:
    """The detail grid behind a 'for developers' expander — one card per real module."""
    status = status or {}
    cards = []
    for rel, name, summ in items:
        label = status.get(name, "")
        cls = _badge_class(label) if label else "muted"
        badge = f'<span class="badge {cls}">{html.escape(label)}</span>' if label else ""
        scls = cls if label else ""
        title = name.replace("ind_", "").replace("_", " ")
        cards.append(
            f'<div class="card scard {scls}"><div class="h">'
            f"<h3>{html.escape(title)}</h3>{badge}</div>"
            f"<p>{html.escape(summ or '—')}</p>"
            f'<p style="margin-top:7px;font-size:12px"><a href="{_GH}/{rel}">{html.escape(rel)} ↗</a></p>'
            "</div>"
        )
    return '<div class="grid ship">' + "".join(cards) + "</div>"


def _hero(state: dict) -> str:
    """Big, friendly header: one-line pitch + live status tiles, each explained."""
    zero = Decimal("0")
    equity = Decimal(str(state.get("equity", "0")))
    peak = Decimal(str(state.get("peak_equity", "0")))
    dd = max(zero, (peak - equity) / peak) if peak > zero else zero
    runs = int(state.get("total_runs", 0))
    halted = str(state.get("apex_halt_env", "")).strip().lower() in (
        "1",
        "true",
        "yes",
        "on",
    ) or bool(state.get("halt_persisted", False))

    pill = (
        '<span class="pill red"><span class="dot"></span>Paused — not trading</span>'
        if halted
        else '<span class="pill"><span class="dot"></span>Running · trading pretend money</span>'
    )

    def tile(k: str, v: str, cap: str) -> str:
        return (
            f'<div class="tile"><div class="k">{k}</div><div class="v">{v}</div>'
            f'<div class="cap">{html.escape(cap)}</div></div>'
        )

    dd_cap = "basically at its high point" if dd < Decimal("0.005") else "below its best value"
    tiles = (
        tile("Account value", _money(equity), "what the practice account is worth now")
        + tile("Trial progress", f"{runs}/{GATE_DAYS} days", "into the 30-day practice run")
        + tile("Best so far", _money(peak), "its highest value to date")
        + tile("Down from peak", f"{dd * 100:.2f}%", dd_cap)
    )
    return (
        '<div class="hero"><h1>⚡ Apex Quant</h1>'
        '<p class="pitch">An app that trades the markets for you, on autopilot — using a "ride the '
        "winners, avoid the losers\" strategy, wrapped in a safety system built so it <b>can't</b> "
        "make a reckless trade. Right now it's trading <b>pretend money</b> (nothing real at risk) "
        "while it proves itself.</p>"
        f"{pill}"
        f'<div class="tiles">{tiles}</div></div>'
    )


def _status_panel(state: dict) -> str:
    """The 'Live status' section: simple chips, the practice-run bar, and any holdings."""
    zero = Decimal("0")
    mode = str(state.get("mode", "paper"))
    broker = str(state.get("broker", "—"))
    equity = Decimal(str(state.get("equity", "0")))
    runs = int(state.get("total_runs", 0))
    frac = min(1.0, runs / GATE_DAYS) if GATE_DAYS else 0.0
    last_ts = str(state.get("last_ts", ""))[:10]
    halted = str(state.get("apex_halt_env", "")).strip().lower() in (
        "1",
        "true",
        "yes",
        "on",
    ) or bool(state.get("halt_persisted", False))

    sc = (
        '<span class="chip red">running? <b>paused</b></span>'
        if halted
        else '<span class="chip ok">running? <b>yes</b></span>'
    )
    chips = (
        f'<div class="bar"><span class="chip">money <b>pretend ({html.escape(mode)})</b></span>'
        f'<span class="chip">broker <b>{html.escape(broker)}</b></span>'
        f'<span class="chip cyn">value <b>{_money(equity)}</b></span>{sc}</div>'
    )
    gate = (
        '<div class="card" style="margin-top:14px">'
        f'<div class="barwrap"><div class="barfill" style="width:{frac * 100:.1f}%"></div></div>'
        f"<div>Practice run: <b>{runs} of {GATE_DAYS} days</b> done "
        f"(last update {html.escape(last_ts or 'n/a')}). It runs once each weekday near the close."
        "</div></div>"
    )

    positions: dict = state.get("positions", {}) or {}
    if positions:
        rows = []
        for ticker, pos in sorted(positions.items()):
            qty = Decimal(str(pos.get("qty", "0")))
            avg = Decimal(str(pos.get("avg_entry_price", "0")))
            cur = Decimal(str(pos.get("current_price", "0")))
            unreal = (cur - avg) * qty
            cls = "pos" if unreal >= zero else "neg"
            rows.append(
                f"<tr><td>{html.escape(ticker)}</td><td>{qty:,.4f}</td>"
                f"<td>{avg:,.2f}</td><td>{cur:,.2f}</td>"
                f'<td class="{cls}">{float(unreal):+,.2f}</td></tr>'
            )
        pos_card = (
            '<div class="card" style="margin-top:14px"><table><tr><th>Holding</th><th>Amount</th>'
            "<th>Bought at</th><th>Now</th><th>Gain/loss</th></tr>"
            + "".join(rows)
            + "</table></div>"
        )
    else:
        pos_card = (
            '<div class="card" style="margin-top:14px"><span class="sub">Nothing held right now '
            "(it only buys when markets are trending up).</span></div>"
        )
    return chips + gate + pos_card


def _blk(sid: str, heading: str, note_html: str, body: str) -> str:
    """A page section: heading + optional (trusted) note paragraph + body."""
    note = f'<p class="note">{note_html}</p>' if note_html else ""
    return f'<section id="{sid}" class="blk"><h2>{html.escape(heading)}</h2>{note}{body}</section>'


def build_site(
    state: dict, sections_data: list[tuple], shipped, progress: str, interactive: bool = False
) -> str:
    """Pure: assemble the whole single-page app from live state + introspected sections."""
    by_sid = {sid: items for sid, _t, _lead, items in sections_data}
    total = sum(len(v) for v in by_sid.values())

    nav_items = [
        ("run", "Run it"),
        ("what", "What it is"),
        ("how", "How it works"),
        ("inside", "What's inside"),
        ("gauntlet", "How we test"),
        ("faq", "Questions"),
        ("status", "Live status"),
    ]
    nav = (
        '<nav class="top">'
        + "".join(f'<a href="#{i}">{html.escape(t)}</a>' for i, t in nav_items)
        + "</nav>"
    )

    readme = (
        '<p class="readme">New here? Just scroll from top to bottom — each section adds a little '
        "more detail, and there's a plain-English glossary near the end. No finance background "
        "needed. Anything labelled “for developers” is safe to skip.</p>"
    )

    steps = (
        '<div class="steps">'
        + "".join(
            f'<div class="step"><span class="num">{n}</span><div class="ic">{ic}</div>'
            f"<h3>{html.escape(t)}</h3><p>{html.escape(d)}</p></div>"
            for n, (ic, t, d) in enumerate(_STEPS, 1)
        )
        + "</div>"
    )

    cap_html = []
    for cid, ic, title, desc, sids in _CAPS:
        items: list[tuple[str, str, str]] = []
        for s in sids:
            items += by_sid.get(s, [])
        status = _STRATEGY_STATUS if "strategies" in sids else None
        cap_html.append(
            f'<div class="cap" id="{cid}"><div class="ic">{ic}</div>'
            f'<h3>{html.escape(title)}<span class="cnt">{len(items)} pieces</span></h3>'
            f"<p>{html.escape(desc)}</p>"
            f"<details><summary>🛠 For developers — show the {len(items)} building blocks</summary>"
            f"{_module_cards(items, status)}</details></div>"
        )
    caps = '<div class="caps">' + "".join(cap_html) + "</div>"

    gates = (
        '<div class="gates2">'
        + "".join(
            f'<div class="gate2"><span class="g">{html.escape(g)}</span>'
            f'<span class="d">{html.escape(d)}</span></div>'
            for g, d in _GATES
        )
        + "</div>"
    )

    faq = (
        '<div class="faq">'
        + "".join(
            f"<details><summary>{html.escape(q)}</summary><p>{html.escape(a)}</p></details>"
            for q, a in _FAQ
        )
        + "</div>"
    )

    gloss = (
        '<div class="gloss">'
        + "".join(
            f'<div class="gterm"><b>{html.escape(term)}</b><span>{html.escape(d)}</span></div>'
            for term, d in _GLOSSARY
        )
        + "</div>"
    )

    phases = (
        '<div class="phases">'
        + "".join(
            f'<div class="phase {cls}"><h3>{html.escape(phase)}</h3><p>{html.escape(text)}</p></div>'
            for phase, cls, text in _ROADMAP
        )
        + "</div>"
    )
    recent = "\n".join(progress.splitlines()[:12])
    updates = (
        '<details style="margin-top:16px"><summary>🛠 For developers — recent technical updates</summary>'
        f'<div class="card"><pre>{html.escape(recent)}</pre></div></details>'
    )

    what = (
        "Apex Quant is an app that <b>trades the markets for you, automatically</b>. It follows a "
        "simple idea — hold things that are going up, avoid things going down — across stocks, "
        "bonds, gold and commodities, and wraps it in a safety system designed so a flawed idea "
        "<b>can't</b> place a bad trade. Right now it trades <b>pretend money</b> — nothing real is "
        "at risk — while it finishes a 30-day trial to prove the results hold up."
    )

    body = (
        _hero(state)
        + readme
        + nav
        + _runit_section(interactive)
        + _blk("what", "What is this?", what, "")
        + _blk("how", "How it works", "Three steps, every trading day.", steps)
        + _blk(
            "inside",
            "What's inside",
            "Six simple parts. Read the short description of each — and only open the "
            "“for developers” detail if you're curious.",
            caps,
        )
        + _blk(
            "gauntlet",
            "How we make sure it works",
            "No strategy is trusted with money until it passes <b>all eight</b> of these tests:",
            gates,
        )
        + _blk("faq", "Common questions", "", faq)
        + _blk(
            "glossary",
            "Words, explained",
            "Plain-English meanings for the few terms used above.",
            gloss,
        )
        + _blk(
            "status",
            "Live status",
            "Straight from the running practice account.",
            _status_panel(state),
        )
        + _blk("roadmap", "Where it's headed", "", phases + updates)
    )

    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="refresh" content="120">
<title>Apex Quant</title>
<style>{_THEME}</style></head>
<body><div class="wrap">
{body}
<div class="foot">Apex Quant · {total} parts under the hood · built for clarity ·
<a href="https://github.com/Dukotah/apex-quant">see the code on GitHub</a></div>
</div></body></html>
"""


def _render(interactive: bool = False) -> str:
    db_path = Path(os.getenv("APEX_STATE_DB", str(DEFAULT_STATE_PATH)))
    mode = os.getenv("APEX_MODE", "paper")
    state = _read_state(db_path, mode) or {"mode": mode, "broker": os.getenv("APEX_BROKER", "")}
    sections_data = [(sid, title, lead, _modules(globs)) for sid, title, globs, lead in SECTIONS]
    return build_site(state, sections_data, _SHIPPED, _recent_progress(limit=40), interactive)


def build_to(path: str | Path) -> Path:
    """Render the whole site to a static HTML file (for GitHub Pages)."""
    out = Path(path)
    if str(out.parent) not in ("", "."):
        out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_render(), encoding="utf-8")
    return out


class _Handler(BaseHTTPRequestHandler):
    def _send(self, code: int, body: bytes, ctype: str = "text/html; charset=utf-8") -> None:
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self) -> None:  # noqa: N802
        from urllib.parse import parse_qs, urlparse

        parsed = urlparse(self.path)
        path = parsed.path

        if path in ("/", "/index.html"):
            self._send(200, _render(interactive=True).encode("utf-8"))
            return

        if path == "/api/strategies":
            import json

            data = json.dumps([{"key": k, "label": label} for k, label, _fn in _RUNNABLE])
            self._send(200, data.encode("utf-8"), "application/json")
            return

        if path == "/api/run":
            key = parse_qs(parsed.query).get("strategy", [""])[0]
            try:
                report, inputs = run_strategy(key)
            except Exception as exc:  # noqa: BLE001 — report the failure to the browser
                self._send(
                    400, f"{type(exc).__name__}: {exc}".encode(), "text/plain; charset=utf-8"
                )
                return
            self._send(200, _result_html(report, inputs).encode("utf-8"))
            return

        self.send_error(404)

    def log_message(self, *_args) -> None:
        pass


def main() -> int:
    try:
        sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
    except Exception:  # noqa: BLE001
        pass
    ap = argparse.ArgumentParser(description="The Apex Quant web app.")
    ap.add_argument("--port", type=int, default=8788)
    ap.add_argument("--host", default="127.0.0.1")
    ap.add_argument("--build", metavar="PATH", help="Render the static site to PATH and exit.")
    args = ap.parse_args()

    if args.build:
        out = build_to(args.build)
        print(f"Apex Quant web app built → {out}", flush=True)
        return 0

    server = ThreadingHTTPServer((args.host, args.port), _Handler)
    url = f"http://{args.host}:{args.port}"
    print(f"Apex Quant web app → {url}   (Ctrl+C to stop)", flush=True)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nstopped.")
    finally:
        server.server_close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
