"""
scripts/webapp.py
=================
Comprehensive STATIC web app for Apex Quant — a single self-contained page that
tours *every* feature in the framework: live status, the full strategy library,
the indicator set, the Validation Gauntlet + statistical tests, the risk core,
execution, data hygiene, analytics, the backtester, core engine, and ops tooling.

It is comprehensive *by construction*: every subsystem section is generated by
walking the real package tree and extracting each module's own docstring summary
(via ``ast`` — no imports, no side effects, no heavy deps), so the app can never
silently drift out of sync with the code. Curated panels (overview, the Gauntlet
gates, architecture, roadmap) add the narrative the docstrings can't.

Stdlib only (``ast`` + ``http.server``) — consistent with the $0-infra principle.
Pages is static-only, so:

  python -m scripts.webapp --build site/index.html   # render the static site (CI / Pages)
  python -m scripts.webapp                           # serve locally on http://127.0.0.1:8788
  python -m scripts.webapp --port 9000

Read-only: it never touches the broker or mutates the state DB.
"""

from __future__ import annotations

import argparse
import ast
import html
import os
import sys
from decimal import Decimal
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

from scripts.dashboard import _CSS, _SHIPPED, _badge_class, _money, _recent_progress
from scripts.status import DEFAULT_STATE_PATH, GATE_DAYS, _read_state

_REPO = Path(__file__).resolve().parent.parent
_GH = "https://github.com/Dukotah/apex-quant/blob/main"

# Extra layout CSS (sidebar nav) appended to the shared dashboard CSS.
_LAYOUT_CSS = """
.app{display:grid;grid-template-columns:212px 1fr;gap:26px;align-items:start}
.nav{position:sticky;top:18px;align-self:start;font-size:13px}
.nav a{display:flex;justify-content:space-between;gap:8px;color:var(--muted);
text-decoration:none;padding:6px 10px;border-radius:7px}
.nav a:hover{background:var(--card);color:var(--ink)}
.nav .n{color:var(--muted);font-size:11px;border:1px solid var(--line);border-radius:999px;padding:0 7px}
.sec{scroll-margin-top:16px}
.lead{color:var(--muted);font-size:13px;margin:-4px 0 12px;max-width:70ch}
.gate{display:flex;gap:10px;align-items:flex-start;padding:9px 12px;border-top:1px solid var(--line)}
.gate .g{color:var(--cyn);font-weight:600;white-space:nowrap;font-variant-numeric:tabular-nums}
.flow{font:12.5px/1.7 ui-monospace,Menlo,Consolas,monospace;color:var(--muted);
background:#0d1117;border:1px solid var(--line);border-radius:8px;padding:14px 16px;overflow:auto}
@media(max-width:780px){.app{grid-template-columns:1fr}.nav{position:static;display:flex;
flex-wrap:wrap;gap:4px;margin-bottom:8px}.nav a{padding:4px 9px}}
"""

# Feature subsystems, each generated from the real module tree. Order = nav order.
# (section id, title, [repo-relative globs], one-line lead)
SECTIONS: list[tuple[str, str, list[str], str]] = [
    (
        "strategies",
        "Strategy library",
        ["apex/strategy/library/*.py"],
        "Pluggable strategies. Each emits SignalEvents only — never orders — so a buggy "
        "strategy has no pathway to the broker. One is deployed live; the rest are tested "
        "research references and candidates.",
    ),
    (
        "indicators",
        "Indicators",
        ["apex/strategy/indicators.py", "apex/strategy/ind_*.py"],
        "Stateless indicator library operating on Decimal series — each tested against "
        "hand-computed values, returning None on insufficient data rather than garbage.",
    ),
    (
        "validation",
        "Validation Gauntlet & statistics",
        ["apex/validation/*.py"],
        "The moat: a strategy must clear the Gauntlet before deployment, plus a deep bench "
        "of statistical edge tests (bootstrap, permutation, deflated Sharpe, regime splits).",
    ),
    (
        "risk",
        "Risk core",
        ["apex/risk/*.py"],
        "The immutable RiskManager is the SOLE producer of orders and sits between intent "
        "and action. Around it: sizing, drawdown throttle, vol-target, exposure, hedging, caps.",
    ),
    (
        "execution",
        "Execution",
        ["apex/execution/*.py"],
        "Approved orders → fills. Paper/live behind one config switch; idempotent, "
        "reconciling, halt-safe (a halt cancels resting orders).",
    ),
    (
        "data",
        "Data & feeds",
        ["apex/data/*.py"],
        "Feeds (historical, Alpaca equities/crypto/options) plus data-hygiene tooling: "
        "normalization, resampling, outlier/winsorize, OHLC consistency, quality checks.",
    ),
    (
        "analytics",
        "Analytics & reporting",
        ["apex/analytics/*.py"],
        "Performance analytics and reporting tables — equity curve, drawdowns, monthly "
        "returns, attribution, rolling beta/correlation, trade analysis.",
    ),
    (
        "backtest",
        "Backtest engine",
        ["apex/backtest/*.py"],
        "Deterministic, no-look-ahead backtester; the Gauntlet runner that feeds all gates; "
        "the multi-strategy allocator; seeded synthetic data.",
    ),
    (
        "core",
        "Core engine",
        ["apex/core/*.py"],
        "The skeleton everything depends on: frozen data models, the event taxonomy, the "
        "event bus, the real/simulated clock, and the config + paper/live MODE switch.",
    ),
    (
        "ops",
        "Operations & tooling",
        ["apex/ops/*.py", "scripts/*.py"],
        "Running the live system: the run_once cron cycle, status/preflight, paper-gate "
        "report, alerts, dashboards, and the research/validation scripts.",
    ),
]

# Curated status overlay for strategies we have a verdict on. Everything else
# renders as a tested research reference.
_STRATEGY_STATUS: dict[str, str] = {
    "multi_asset_trend": "LIVE",
    "cross_asset_value": "CANDIDATE",
    "ts_momentum_blend": "ARCHIVED",
    "value_momentum": "research",
    "cross_sectional_momentum": "research",
    "short_term_reversal": "research",
    "bond_carry": "research",
    "breadth_momentum": "research",
    "credit_spread": "research",
    "turn_of_month": "research",
    "options_income": "gated",
    "long_short_momentum": "gated",
}

# The Validation Gauntlet, in order. (label, what it proves)
_GATES: list[tuple[str, str]] = [
    ("Gate 1 · Sharpe/Sortino/DD", "In-sample risk-adjusted return and drawdown clear the bar."),
    ("Gate 2 · Overfit guard", "Out-of-sample performance doesn't collapse vs in-sample."),
    ("Gate 3 · Walk-forward", "Rolling out-of-sample windows stay positive (efficiency ratio)."),
    (
        "Gate 4 · Monte Carlo",
        "Resampled trade order — is the edge real or a lucky sequence (p-value)?",
    ),
    ("Gate 5 · MCPT permutation", "Price-path permutation: the signal beats shuffled noise."),
    ("Gate 6 · Cost-stress @ 2×", "Survives double the modeled slippage + commission."),
    ("Gate 7 · Beats SPY", "Out-earns buy-and-hold on a risk-adjusted basis."),
    (
        "Gate 8 · Deflated Sharpe (soft)",
        "PSR / Deflated Sharpe vs the number of trials — WARN-only.",
    ),
]

# Curated roadmap snapshot (see docs/ROADMAP-STRATEGIC.md for the full plan).
_ROADMAP: list[tuple[str, str, str]] = [
    (
        "NOW",
        "ok",
        "Go-live hardening DONE: preflight broker check, live-switch CI gate, "
        "vol-target config, daily-loss baseline, halt-cancels-orders, reconciliation diff.",
    ),
    (
        "NOW",
        "work",
        "Run out the 30-day paper gate (time-gated) — the last thing before live capital.",
    ),
    (
        "NEXT",
        "behind",
        "HARD BLOCKER: move the state store off the public repo before any live dollar.",
    ),
    (
        "NEXT",
        "work",
        "Pilot live at 10–25%; per-sleeve P&L attribution; dead-man's switch; free W8 stress.",
    ),
    (
        "LATER",
        "work",
        "Pay-for-data decision → survivorship-free value Gauntlet → fund the 2nd edge (80/20).",
    ),
    (
        "HORIZON",
        "muted",
        "Carry sleeve, regime detection, options live, long/short, apex-trader API.",
    ),
]


# --------------------------------------------------------------- introspection


def _summary(path: Path) -> str:
    """First descriptive sentence of a module's docstring (no import, via ast)."""
    try:
        doc = ast.get_docstring(ast.parse(path.read_text(encoding="utf-8"))) or ""
    except (OSError, SyntaxError, ValueError):
        return ""
    out: list[str] = []
    for raw in doc.splitlines():
        ln = raw.strip()
        if not ln:
            if out:
                break
            continue
        if ln.endswith(".py") or (set(ln) <= set("=-~_")):  # skip path header + underline
            continue
        out.append(ln)
        if ln.endswith(".") or len(" ".join(out)) > 170:
            break
    return " ".join(out)[:220]


def _modules(globs: list[str]) -> list[tuple[str, str, str]]:
    """(repo-relative path, stem, summary) for every non-dunder module in `globs`."""
    seen: set[Path] = set()
    items: list[tuple[str, str, str]] = []
    for g in globs:
        for p in sorted(_REPO.glob(g)):
            if p.name.startswith("__") or p in seen:
                continue
            seen.add(p)
            items.append((p.relative_to(_REPO).as_posix(), p.stem, _summary(p)))
    return items


# ------------------------------------------------------------------- rendering


def _module_cards(items: list[tuple[str, str, str]], status: dict[str, str] | None = None) -> str:
    status = status or {}
    cards = []
    for rel, name, summ in items:
        label = status.get(name, "")
        cls = _badge_class(label) if label else "muted"
        badge = f'<span class="badge {cls}">{html.escape(label)}</span>' if label else ""
        scls = cls if label else ""
        title = name.replace("ind_", "").replace("_", " ")
        cards.append(
            f'<div class="card scard {scls}"><div class="h">'
            f"<h3>{html.escape(title)}</h3>{badge}</div>"
            f"<p>{html.escape(summ or '—')}</p>"
            f'<p style="margin-top:7px;font-size:12px"><a href="{_GH}/{rel}">{html.escape(rel)} ↗</a></p>'
            "</div>"
        )
    return '<div class="grid ship">' + "".join(cards) + "</div>"


def _overview(state: dict) -> str:
    """The live paper-status panel: chips + account stats + paper-gate bar + positions."""
    zero = Decimal("0")
    mode = str(state.get("mode", "paper"))
    broker = str(state.get("broker", "—"))
    equity = Decimal(str(state.get("equity", "0")))
    peak = Decimal(str(state.get("peak_equity", "0")))
    cash = Decimal(str(state.get("cash", "0")))
    dd = max(zero, (peak - equity) / peak) if peak > zero else zero
    halted = str(state.get("apex_halt_env", "")).strip().lower() in (
        "1",
        "true",
        "yes",
        "on",
    ) or bool(state.get("halt_persisted", False))
    runs = int(state.get("total_runs", 0))
    frac = min(1.0, runs / GATE_DAYS) if GATE_DAYS else 0.0
    last_ts = str(state.get("last_ts", ""))[:10]

    chip = (
        '<span class="chip red">status <b>HALTED</b></span>'
        if halted
        else '<span class="chip ok">status <b>armed</b></span>'
    )
    chips = (
        f'<div class="bar"><span class="chip">mode <b>{html.escape(mode)}</b></span>'
        f'<span class="chip">broker <b>{html.escape(broker)}</b></span>'
        f'<span class="chip cyn">equity <b>{_money(equity)}</b></span>'
        f'<span class="chip">drawdown <b>{dd * 100:.2f}%</b></span>'
        f'<span class="chip">gate <b>{runs}/{GATE_DAYS}</b></span>{chip}</div>'
    )

    def stat(k: str, v: str) -> str:
        return f'<div class="card stat"><div class="k">{k}</div><div class="v">{v}</div></div>'

    stats = (
        '<div class="grid">'
        + stat("Equity", _money(equity))
        + stat("Peak", _money(peak))
        + stat("Cash", _money(cash))
        + stat("Drawdown", f"{dd * 100:.2f}%")
        + "</div>"
    )
    gate = (
        '<div class="card" style="margin-top:12px">'
        f'<div class="barwrap"><div class="barfill" style="width:{frac * 100:.1f}%"></div></div>'
        f"<div>Paper gate {runs}/{GATE_DAYS} days · multi-asset trend live on paper "
        f"(as of {html.escape(last_ts or 'n/a')})</div></div>"
    )
    return chips + stats + gate


def _section(sid: str, title: str, lead: str, body: str) -> str:
    return (
        f'<section id="{sid}" class="sec"><h2>{html.escape(title)}</h2>'
        f'<p class="lead">{html.escape(lead)}</p>{body}</section>'
    )


def build_site(state: dict, sections_data: list[tuple], shipped, progress: str) -> str:
    """Pure: assemble the whole single-page app from the live state + introspected sections."""
    # Nav (overview + architecture + each subsystem + gauntlet + roadmap + progress).
    nav_items = [("overview", "Overview", ""), ("architecture", "How it works", "")]
    for sid, title, _lead, items in sections_data:
        nav_items.append((sid, title, str(len(items))))
    nav_items += [("roadmap", "Roadmap", ""), ("progress", "Progress", "")]
    nav_links = []
    for sid, t, n in nav_items:
        cnt = f'<span class="n">{n}</span>' if n else ""
        nav_links.append(f'<a href="#{sid}">{html.escape(t)}{cnt}</a>')
    nav = '<nav class="nav">' + "".join(nav_links) + "</nav>"

    total = sum(len(items) for _, _, _, items in sections_data)

    # Curated: architecture / data flow.
    flow = html.escape(
        "DataFeed.stream() ──▶ MarketEvent\n"
        "   └─▶ Strategy.on_bar() ──▶ SignalEvent        (intent only)\n"
        "          └─▶ RiskManager.evaluate()            (sole order producer; fails closed)\n"
        "                 ├─ any check fails ─▶ None      (no trade)\n"
        "                 └─ all pass ─▶ OrderEvent ──▶ ExecutionEngine ──▶ FillEvent\n"
        "                                                      └─▶ Portfolio  ──┐\n"
        "                          equity / drawdown feeds back to RiskManager ◀┘"
    )
    architecture = _section(
        "architecture",
        "How it works",
        "Modules talk only through events. Strategies express intent; the immutable "
        "RiskManager is the one place orders are born and cannot be bypassed. Money is "
        "Decimal, models are frozen, the backtest is deterministic, paper→live is config-only.",
        f'<div class="flow">{flow}</div>',
    )

    # Curated: Gauntlet gates panel (rendered inside the validation section).
    gates_panel = (
        '<div class="card" style="margin-bottom:12px"><div class="k" style="color:var(--muted);'
        'font-size:11.5px;text-transform:uppercase;letter-spacing:.05em">The Gauntlet — every '
        "strategy must clear these</div>"
        + "".join(
            f'<div class="gate"><span class="g">{html.escape(g)}</span>'
            f"<span style='color:var(--muted)'>{html.escape(d)}</span></div>"
            for g, d in _GATES
        )
        + "</div>"
    )

    # Build each generated subsystem section.
    body_sections = [
        _section(
            "overview",
            "Overview",
            "Live paper status of the deployed "
            "multi-asset trend bot, and the road to live capital.",
            _overview(state),
        ),
        architecture,
    ]
    for sid, title, lead, items in sections_data:
        status = _STRATEGY_STATUS if sid == "strategies" else None
        cards = _module_cards(items, status)
        pre = gates_panel if sid == "validation" else ""
        # shipped highlights appear under strategies for context
        body_sections.append(_section(sid, title, lead, pre + cards))

    # Curated: roadmap.
    road = "".join(
        f'<div class="card scard {cls}"><div class="h"><h3>{html.escape(phase)}</h3>'
        f'<span class="badge {cls}">{html.escape(phase)}</span></div>'
        f"<p>{html.escape(text)}</p></div>"
        for phase, cls, text in _ROADMAP
    )
    body_sections.append(
        _section(
            "roadmap",
            "Roadmap",
            "The forward plan of record (docs/ROADMAP-STRATEGIC.md). Two critical paths: "
            "live capital, and a survivorship-honest second edge.",
            '<div class="grid ship">' + road + "</div>",
        )
    )

    # Shipped highlights + progress.
    ship_cards = "".join(
        f'<div class="card scard {_badge_class(s)}"><div class="h"><h3>{html.escape(t)}</h3>'
        f'<span class="badge {_badge_class(s)}">{html.escape(s)}</span></div>'
        f"<p>{html.escape(d)}</p></div>"
        for t, s, d in shipped
    )
    body_sections.append(
        _section(
            "progress",
            "Shipped & recent progress",
            "Headline results and the running PROGRESS.md log.",
            '<div class="grid ship">'
            + ship_cards
            + "</div>"
            + f'<div class="card" style="margin-top:12px"><pre>{html.escape(progress)}</pre></div>',
        )
    )

    body = "".join(body_sections)
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="refresh" content="120">
<title>Apex Quant — Web App</title>
<style>{_CSS}{_LAYOUT_CSS}</style></head>
<body><div class="wrap">
  <h1>⚡ Apex Quant</h1>
  <p class="sub">event-driven, fail-closed algo-trading framework · {total} modules across
    {len(sections_data)} subsystems · <a href="https://github.com/Dukotah/apex-quant">repo ↗</a></p>
  <div class="app">
    {nav}
    <main>{body}</main>
  </div>
  <div class="foot">Apex Quant · generated from the live source tree ·
    <a href="https://github.com/Dukotah/apex-quant">github.com/Dukotah/apex-quant</a></div>
</div></body></html>
"""


def _render() -> str:
    db_path = Path(os.getenv("APEX_STATE_DB", str(DEFAULT_STATE_PATH)))
    mode = os.getenv("APEX_MODE", "paper")
    state = _read_state(db_path, mode) or {"mode": mode, "broker": os.getenv("APEX_BROKER", "")}
    sections_data = [(sid, title, lead, _modules(globs)) for sid, title, globs, lead in SECTIONS]
    return build_site(state, sections_data, _SHIPPED, _recent_progress(limit=40))


def build_to(path: str | Path) -> Path:
    """Render the whole site to a static HTML file (for GitHub Pages)."""
    out = Path(path)
    if str(out.parent) not in ("", "."):
        out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_render(), encoding="utf-8")
    return out


class _Handler(BaseHTTPRequestHandler):
    def do_GET(self) -> None:  # noqa: N802
        if self.path not in ("/", "/index.html"):
            self.send_error(404)
            return
        body = _render().encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, *_args) -> None:
        pass


def main() -> int:
    try:
        sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
    except Exception:  # noqa: BLE001
        pass
    ap = argparse.ArgumentParser(description="Comprehensive web app for Apex Quant.")
    ap.add_argument("--port", type=int, default=8788)
    ap.add_argument("--host", default="127.0.0.1")
    ap.add_argument("--build", metavar="PATH", help="Render the static site to PATH and exit.")
    args = ap.parse_args()

    if args.build:
        out = build_to(args.build)
        print(f"Apex Quant web app built → {out}", flush=True)
        return 0

    server = ThreadingHTTPServer((args.host, args.port), _Handler)
    url = f"http://{args.host}:{args.port}"
    print(f"Apex Quant web app → {url}   (Ctrl+C to stop)", flush=True)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nstopped.")
    finally:
        server.server_close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
