"""
scripts/webapp.py
=================
The Apex Quant web app — a polished, plain-language single page that explains the
whole system to a newcomer and lets them drill into the detail if they want.

It is built for *understanding*: a hero with the live paper status, a "how it
works in three steps" explainer, six friendly capability tiles, a plain-English
walk-through of how strategies are tested, and the roadmap. Every technical
detail is still there — the full module list for each capability is tucked behind
an expander (progressive disclosure), generated by introspecting each module's
own docstring via ``ast`` so the app can never drift out of sync with the code.

Stdlib only (``ast`` + ``http.server``) — consistent with the $0-infra principle.
Pages is static-only, so:

  python -m scripts.webapp --build site/index.html   # render the static site (CI / Pages)
  python -m scripts.webapp                           # serve locally on http://127.0.0.1:8788
  python -m scripts.webapp --port 9000

Read-only: it never touches the broker or mutates the state DB.
"""

from __future__ import annotations

import argparse
import ast
import html
import os
import sys
from decimal import Decimal
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

from scripts.dashboard import _CSS, _SHIPPED, _badge_class, _money, _recent_progress
from scripts.status import DEFAULT_STATE_PATH, GATE_DAYS, _read_state

_REPO = Path(__file__).resolve().parent.parent
_GH = "https://github.com/Dukotah/apex-quant/blob/main"

# Polished, plain-language UI theme (hero, sticky nav, how-it-works steps,
# capability tiles with progressive-disclosure expanders, friendly gates/roadmap).
_UI_CSS = """
.hero{background:linear-gradient(155deg,#13294a 0%,#0d1117 62%);border:1px solid var(--line);
border-radius:18px;padding:34px 28px;margin:8px 0 8px}
.hero h1{font-size:32px;line-height:1.1;margin:0 0 10px;letter-spacing:-.02em}
.hero .pitch{color:#cdd9e5;font-size:17px;line-height:1.6;max-width:62ch;margin:0 0 18px}
.pill{display:inline-flex;align-items:center;gap:8px;font-size:13px;padding:6px 13px;border-radius:999px;
border:1px solid #1f6f33;color:var(--grn);background:#0e2417}
.pill.red{border-color:#7a2620;color:var(--red);background:#2a1513}
.pill .dot{width:8px;height:8px;border-radius:50%;background:currentColor}
.tiles{display:grid;grid-template-columns:repeat(auto-fit,minmax(158px,1fr));gap:12px;margin-top:20px}
.tile{background:#0d111799;border:1px solid var(--line);border-radius:13px;padding:15px 17px}
.tile .k{color:var(--muted);font-size:11.5px;text-transform:uppercase;letter-spacing:.05em}
.tile .v{font-size:25px;font-weight:700;margin-top:5px;font-variant-numeric:tabular-nums}
.tile .v.sm{font-size:16px;font-weight:600}
nav.top{display:flex;flex-wrap:wrap;gap:6px;margin:0 0 26px;position:sticky;top:0;z-index:5;
background:#0d1117e6;backdrop-filter:blur(8px);padding:11px 0;border-bottom:1px solid var(--line)}
nav.top a{color:var(--muted);text-decoration:none;font-size:13.5px;padding:6px 13px;border-radius:9px}
nav.top a:hover{background:var(--card);color:var(--ink)}
section.blk{margin:0 0 44px;scroll-margin-top:70px}
section.blk>h2{font-size:19px;text-transform:none;letter-spacing:-.01em;color:var(--ink);
border:0;padding:0;margin:0 0 8px}
.note{color:#aeb9c4;font-size:14.5px;max-width:72ch;margin:0 0 18px;line-height:1.65}
.note b{color:var(--ink)}
.steps{display:grid;grid-template-columns:repeat(auto-fit,minmax(238px,1fr));gap:14px}
.step{background:var(--card);border:1px solid var(--line);border-radius:13px;padding:18px}
.step .ic{font-size:27px}
.step .num{float:right;color:var(--muted);font-size:12px;border:1px solid var(--line);border-radius:999px;
width:23px;height:23px;display:inline-flex;align-items:center;justify-content:center}
.step h3{margin:11px 0 6px;font-size:16px}
.step p{margin:0;color:var(--muted);font-size:13.5px;line-height:1.55}
.caps{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:14px}
.cap{background:var(--card);border:1px solid var(--line);border-radius:13px;padding:18px}
.cap .ic{font-size:25px}
.cap h3{margin:9px 0 4px;font-size:16px;display:flex;justify-content:space-between;align-items:center;gap:8px}
.cap .cnt{font-size:12px;color:var(--cyn);border:1px solid #1f4a80;border-radius:999px;padding:1px 10px;
white-space:nowrap}
.cap>p{margin:0 0 12px;color:var(--muted);font-size:13.5px;line-height:1.55}
details{border-top:1px solid var(--line);padding-top:11px}
details summary{cursor:pointer;color:var(--cyn);font-size:13px;list-style:none}
details summary::-webkit-details-marker{display:none}
details summary:hover{color:#79c0ff}
details[open] summary{margin-bottom:12px}
.gates2{display:grid;gap:8px}
.gate2{display:flex;flex-wrap:wrap;gap:6px 14px;background:var(--card);border:1px solid var(--line);
border-radius:11px;padding:13px 15px}
.gate2 .g{color:var(--cyn);font-weight:600;min-width:172px}
.gate2 .d{color:var(--muted);font-size:13.5px;flex:1}
.phases{display:grid;grid-template-columns:repeat(auto-fit,minmax(262px,1fr));gap:14px}
.phase{background:var(--card);border:1px solid var(--line);border-left:4px solid var(--muted);
border-radius:13px;padding:17px}
.phase.ok{border-left-color:var(--grn)}.phase.work{border-left-color:var(--yel)}
.phase.behind{border-left-color:var(--red)}
.phase h3{margin:0 0 7px;font-size:13px;text-transform:uppercase;letter-spacing:.05em}
.phase p{margin:0;color:var(--muted);font-size:13.5px;line-height:1.55}
@media(max-width:640px){.hero{padding:24px 18px}.hero h1{font-size:25px}.hero .pitch{font-size:15px}}
"""

# Subsystems generated from the real module tree. (sid, title, [globs], lead)
SECTIONS: list[tuple[str, str, list[str], str]] = [
    ("strategies", "Strategies", ["apex/strategy/library/*.py"], ""),
    ("indicators", "Indicators", ["apex/strategy/indicators.py", "apex/strategy/ind_*.py"], ""),
    ("validation", "Validation", ["apex/validation/*.py"], ""),
    ("risk", "Risk", ["apex/risk/*.py"], ""),
    ("execution", "Execution", ["apex/execution/*.py"], ""),
    ("data", "Data", ["apex/data/*.py"], ""),
    ("analytics", "Analytics", ["apex/analytics/*.py"], ""),
    ("backtest", "Backtest", ["apex/backtest/*.py"], ""),
    ("core", "Core", ["apex/core/*.py"], ""),
    ("ops", "Ops", ["apex/ops/*.py", "scripts/*.py"], ""),
]

# Curated status overlay for strategies we have a verdict on; the rest render as
# tested research references.
_STRATEGY_STATUS: dict[str, str] = {
    "multi_asset_trend": "LIVE",
    "cross_asset_value": "CANDIDATE",
    "ts_momentum_blend": "ARCHIVED",
    "value_momentum": "research",
    "cross_sectional_momentum": "research",
    "short_term_reversal": "research",
    "bond_carry": "research",
    "breadth_momentum": "research",
    "credit_spread": "research",
    "turn_of_month": "research",
    "options_income": "gated",
    "long_short_momentum": "gated",
}

# Friendly, plain-language capability tiles. Each aggregates one or more
# subsystem sids; (cap id, icon, title, plain description, [member sids]).
_CAPS: list[tuple[str, str, str, str, list[str]]] = [
    (
        "strategies",
        "📈",
        "Strategies",
        "The trading playbooks. Each one watches the market and only ever SUGGESTS a "
        "trade — it can never place one itself, so a bad idea can't reach the broker.",
        ["strategies", "indicators"],
    ),
    (
        "safety",
        "🛡️",
        "Safety & risk",
        "One gatekeeper that cannot be bypassed: it sizes every trade, insists on a "
        "stop-loss, caps exposure, and halts everything if losses pile up.",
        ["risk", "execution"],
    ),
    (
        "validation",
        "🔬",
        "Testing & proof",
        "Before a strategy risks a cent it must survive a battery of tests built to expose "
        "luck, overfitting and hidden trading costs.",
        ["validation", "backtest"],
    ),
    (
        "data",
        "🗄️",
        "Market data",
        "Clean, trustworthy prices — fetched, normalized and sanity-checked before the "
        "system ever acts on them.",
        ["data"],
    ),
    (
        "analytics",
        "📊",
        "Analytics",
        "Plain-English performance reporting: returns, drawdowns, win/loss, and what is "
        "actually driving the results.",
        ["analytics"],
    ),
    (
        "ops",
        "⚙️",
        "Operations",
        "The autopilot: it runs once a day on a free schedule, watches itself, keeps an "
        "audit trail, and pings you if anything looks off.",
        ["ops", "core"],
    ),
]

# How it works, in three plain steps. (icon, title, description)
_STEPS: list[tuple[str, str, str]] = [
    (
        "🔍",
        "Spot",
        "Each day the strategies scan the market and flag opportunities — as suggestions only.",
    ),
    (
        "🛡️",
        "Check",
        "The risk gatekeeper checks every suggestion: right size? stop-loss attached? within limits? Anything unsafe becomes “no trade.”",
    ),
    (
        "✅",
        "Trade",
        "Approved orders go to the broker (paper money for now) and every result is tracked, every day.",
    ),
]

# The Gauntlet, in order. (label, plain-English meaning)
_GATES: list[tuple[str, str]] = [
    (
        "Gate 1 · Returns vs risk",
        "Does it earn enough for the bumpiness and worst-case loss it takes on?",
    ),
    (
        "Gate 2 · Overfit guard",
        "Does it still work on data it was never tuned on, or did we fool ourselves?",
    ),
    (
        "Gate 3 · Walk-forward",
        "Retested again and again on later, unseen periods — does it keep holding up?",
    ),
    (
        "Gate 4 · Monte Carlo",
        "Shuffle the trades thousands of times — is the edge real, or one lucky run?",
    ),
    ("Gate 5 · Permutation", "Scramble the price history — can it still beat pure noise?"),
    ("Gate 6 · Cost stress", "Does it survive double the real-world trading costs?"),
    ("Gate 7 · Beats the market", "Does it out-earn simply buying and holding the S&P 500?"),
    (
        "Gate 8 · Luck adjustment",
        "Discounts the score for how many ideas we tried (a soft warning).",
    ),
]

# Plain-language roadmap. (phase, colour class, text)
_ROADMAP: list[tuple[str, str, str]] = [
    (
        "Done",
        "ok",
        "Built the engine, the unbypassable safety system, and a working trend "
        "strategy. It's live on paper, and the go-live safety checks are complete.",
    ),
    (
        "Now",
        "work",
        "Finishing a 30-day paper trial. When it passes, start trading a small "
        "amount of real money — but first move the records off the public repo.",
    ),
    (
        "Later",
        "muted",
        "Add a second, independent strategy and let a capital allocator split "
        "money between them; then explore options, carry, and more.",
    ),
]


# --------------------------------------------------------------- introspection


def _summary(path: Path) -> str:
    """First descriptive line of a module's docstring (no import, via ast)."""
    try:
        doc = ast.get_docstring(ast.parse(path.read_text(encoding="utf-8"))) or ""
    except (OSError, SyntaxError, ValueError):
        return ""
    out: list[str] = []
    for raw in doc.splitlines():
        ln = raw.strip()
        if not ln:
            if out:
                break
            continue
        if ln.endswith(".py") or (set(ln) <= set("=-~_")):  # skip path header + underline
            continue
        out.append(ln)
        if ln.endswith(".") or len(" ".join(out)) > 170:
            break
    return " ".join(out)[:220]


def _modules(globs: list[str]) -> list[tuple[str, str, str]]:
    """(repo-relative path, stem, summary) for every non-dunder module in `globs`."""
    seen: set[Path] = set()
    items: list[tuple[str, str, str]] = []
    for g in globs:
        for p in sorted(_REPO.glob(g)):
            if p.name.startswith("__") or p in seen:
                continue
            seen.add(p)
            items.append((p.relative_to(_REPO).as_posix(), p.stem, _summary(p)))
    return items


# ------------------------------------------------------------------- rendering


def _module_cards(items: list[tuple[str, str, str]], status: dict[str, str] | None = None) -> str:
    """The detail grid behind a capability's expander — one card per real module."""
    status = status or {}
    cards = []
    for rel, name, summ in items:
        label = status.get(name, "")
        cls = _badge_class(label) if label else "muted"
        badge = f'<span class="badge {cls}">{html.escape(label)}</span>' if label else ""
        scls = cls if label else ""
        title = name.replace("ind_", "").replace("_", " ")
        cards.append(
            f'<div class="card scard {scls}"><div class="h">'
            f"<h3>{html.escape(title)}</h3>{badge}</div>"
            f"<p>{html.escape(summ or '—')}</p>"
            f'<p style="margin-top:7px;font-size:12px"><a href="{_GH}/{rel}">{html.escape(rel)} ↗</a></p>'
            "</div>"
        )
    return '<div class="grid ship">' + "".join(cards) + "</div>"


def _hero(state: dict) -> str:
    """Big, friendly header: one-line pitch + live paper-status tiles."""
    zero = Decimal("0")
    equity = Decimal(str(state.get("equity", "0")))
    peak = Decimal(str(state.get("peak_equity", "0")))
    dd = max(zero, (peak - equity) / peak) if peak > zero else zero
    runs = int(state.get("total_runs", 0))
    halted = str(state.get("apex_halt_env", "")).strip().lower() in (
        "1",
        "true",
        "yes",
        "on",
    ) or bool(state.get("halt_persisted", False))

    pill = (
        '<span class="pill red"><span class="dot"></span>Halted — not trading</span>'
        if halted
        else '<span class="pill"><span class="dot"></span>Live · trading paper money</span>'
    )

    def tile(k: str, v: str) -> str:
        return f'<div class="tile"><div class="k">{k}</div><div class="v">{v}</div></div>'

    tiles = (
        tile("Account value", _money(equity))
        + tile("Trial progress", f"{runs}/{GATE_DAYS} days")
        + tile("Best so far", _money(peak))
        + tile("Down from peak", f"{dd * 100:.2f}%")
    )
    return (
        '<div class="hero"><h1>⚡ Apex Quant</h1>'
        '<p class="pitch">An automated trading system that runs a diversified, trend-following '
        "strategy on autopilot — with a safety layer built so a flawed strategy <b>physically "
        "cannot</b> place a reckless trade. It is trading <b>paper money</b> (nothing real at "
        "risk) while it proves itself.</p>"
        f"{pill}"
        f'<div class="tiles">{tiles}</div></div>'
    )


def _status_panel(state: dict) -> str:
    """The 'Live status' section: mode/broker chips, paper-gate bar, positions."""
    zero = Decimal("0")
    mode = str(state.get("mode", "paper"))
    broker = str(state.get("broker", "—"))
    equity = Decimal(str(state.get("equity", "0")))
    runs = int(state.get("total_runs", 0))
    frac = min(1.0, runs / GATE_DAYS) if GATE_DAYS else 0.0
    last_ts = str(state.get("last_ts", ""))[:10]
    halted = str(state.get("apex_halt_env", "")).strip().lower() in (
        "1",
        "true",
        "yes",
        "on",
    ) or bool(state.get("halt_persisted", False))

    sc = (
        '<span class="chip red">status <b>HALTED</b></span>'
        if halted
        else '<span class="chip ok">status <b>armed</b></span>'
    )
    chips = (
        f'<div class="bar"><span class="chip">mode <b>{html.escape(mode)}</b></span>'
        f'<span class="chip">broker <b>{html.escape(broker)}</b></span>'
        f'<span class="chip cyn">value <b>{_money(equity)}</b></span>{sc}</div>'
    )
    gate = (
        '<div class="card" style="margin-top:12px">'
        f'<div class="barwrap"><div class="barfill" style="width:{frac * 100:.1f}%"></div></div>'
        f"<div>Paper trial: {runs} of {GATE_DAYS} days "
        f"(as of {html.escape(last_ts or 'n/a')}). The bot runs once each weekday near the close."
        "</div></div>"
    )

    positions: dict = state.get("positions", {}) or {}
    if positions:
        rows = []
        for ticker, pos in sorted(positions.items()):
            qty = Decimal(str(pos.get("qty", "0")))
            avg = Decimal(str(pos.get("avg_entry_price", "0")))
            cur = Decimal(str(pos.get("current_price", "0")))
            unreal = (cur - avg) * qty
            cls = "pos" if unreal >= zero else "neg"
            rows.append(
                f"<tr><td>{html.escape(ticker)}</td><td>{qty:,.4f}</td>"
                f"<td>{avg:,.2f}</td><td>{cur:,.2f}</td>"
                f'<td class="{cls}">{float(unreal):+,.2f}</td></tr>'
            )
        pos_card = (
            '<div class="card" style="margin-top:12px"><table><tr><th>Holding</th><th>Qty</th>'
            "<th>Avg cost</th><th>Price</th><th>Gain/loss</th></tr>"
            + "".join(rows)
            + "</table></div>"
        )
    else:
        pos_card = '<div class="card" style="margin-top:12px"><div class="sub" style="margin:0">no open positions right now</div></div>'

    return chips + gate + pos_card


def _blk(sid: str, heading: str, note_html: str, body: str) -> str:
    """A page section: heading + optional (trusted) note paragraph + body."""
    note = f'<p class="note">{note_html}</p>' if note_html else ""
    return f'<section id="{sid}" class="blk"><h2>{html.escape(heading)}</h2>{note}{body}</section>'


def build_site(state: dict, sections_data: list[tuple], shipped, progress: str) -> str:
    """Pure: assemble the whole single-page app from live state + introspected sections."""
    by_sid = {sid: items for sid, _t, _lead, items in sections_data}
    total = sum(len(v) for v in by_sid.values())

    nav_items = [
        ("what", "What it is"),
        ("how", "How it works"),
        ("inside", "What's inside"),
        ("gauntlet", "How we test"),
        ("status", "Live status"),
        ("roadmap", "Roadmap"),
    ]
    nav = (
        '<nav class="top">'
        + "".join(f'<a href="#{i}">{html.escape(t)}</a>' for i, t in nav_items)
        + "</nav>"
    )

    # How it works — three steps.
    steps = (
        '<div class="steps">'
        + "".join(
            f'<div class="step"><span class="num">{n}</span><div class="ic">{ic}</div>'
            f"<h3>{html.escape(t)}</h3><p>{html.escape(d)}</p></div>"
            for n, (ic, t, d) in enumerate(_STEPS, 1)
        )
        + "</div>"
    )

    # Capability tiles with progressive-disclosure detail.
    cap_html = []
    for cid, ic, title, desc, sids in _CAPS:
        items: list[tuple[str, str, str]] = []
        for s in sids:
            items += by_sid.get(s, [])
        status = _STRATEGY_STATUS if "strategies" in sids else None
        cap_html.append(
            f'<div class="cap" id="{cid}"><div class="ic">{ic}</div>'
            f'<h3>{html.escape(title)}<span class="cnt">{len(items)} pieces</span></h3>'
            f"<p>{html.escape(desc)}</p>"
            f"<details><summary>Show the {len(items)} building blocks ↓</summary>"
            f"{_module_cards(items, status)}</details></div>"
        )
    caps = '<div class="caps">' + "".join(cap_html) + "</div>"

    # The Gauntlet, in plain language.
    gates = (
        '<div class="gates2">'
        + "".join(
            f'<div class="gate2"><span class="g">{html.escape(g)}</span>'
            f'<span class="d">{html.escape(d)}</span></div>'
            for g, d in _GATES
        )
        + "</div>"
    )

    # Roadmap + a collapsed, technical "recent updates" log for the curious.
    phases = (
        '<div class="phases">'
        + "".join(
            f'<div class="phase {cls}"><h3>{html.escape(phase)}</h3><p>{html.escape(text)}</p></div>'
            for phase, cls, text in _ROADMAP
        )
        + "</div>"
    )
    recent = "\n".join(progress.splitlines()[:12])
    updates = (
        '<details style="margin-top:14px"><summary>Recent technical updates ↓</summary>'
        f'<div class="card"><pre>{html.escape(recent)}</pre></div></details>'
    )

    what = (
        "Apex Quant is an <b>automated trading system</b>. It runs a diversified, trend-"
        "following strategy on autopilot, with a safety layer designed so a buggy or reckless "
        "strategy literally has no way to place a bad trade. Right now it trades <b>paper money</b>"
        " — nothing real is at risk — while it completes a 30-day trial to prove the results hold "
        "up live."
    )

    body = (
        _hero(state)
        + nav
        + _blk("what", "What is this?", what, "")
        + _blk("how", "How it works", "Three steps, every trading day.", steps)
        + _blk(
            "inside",
            "What's inside",
            f"{total} building blocks, grouped into six parts. Open any group to see the detail.",
            caps,
        )
        + _blk(
            "gauntlet",
            "How we test a strategy",
            "No strategy is trusted with money until it clears <b>all</b> of these:",
            gates,
        )
        + _blk(
            "status",
            "Live status",
            "Straight from the running paper account.",
            _status_panel(state),
        )
        + _blk("roadmap", "Where it's headed", "", phases + updates)
    )

    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="refresh" content="120">
<title>Apex Quant</title>
<style>{_CSS}{_UI_CSS}</style></head>
<body><div class="wrap">
{body}
<div class="foot">Apex Quant · {total} modules · generated from the live source ·
<a href="https://github.com/Dukotah/apex-quant">github.com/Dukotah/apex-quant</a></div>
</div></body></html>
"""


def _render() -> str:
    db_path = Path(os.getenv("APEX_STATE_DB", str(DEFAULT_STATE_PATH)))
    mode = os.getenv("APEX_MODE", "paper")
    state = _read_state(db_path, mode) or {"mode": mode, "broker": os.getenv("APEX_BROKER", "")}
    sections_data = [(sid, title, lead, _modules(globs)) for sid, title, globs, lead in SECTIONS]
    return build_site(state, sections_data, _SHIPPED, _recent_progress(limit=40))


def build_to(path: str | Path) -> Path:
    """Render the whole site to a static HTML file (for GitHub Pages)."""
    out = Path(path)
    if str(out.parent) not in ("", "."):
        out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_render(), encoding="utf-8")
    return out


class _Handler(BaseHTTPRequestHandler):
    def do_GET(self) -> None:  # noqa: N802
        if self.path not in ("/", "/index.html"):
            self.send_error(404)
            return
        body = _render().encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, *_args) -> None:
        pass


def main() -> int:
    try:
        sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
    except Exception:  # noqa: BLE001
        pass
    ap = argparse.ArgumentParser(description="The Apex Quant web app.")
    ap.add_argument("--port", type=int, default=8788)
    ap.add_argument("--host", default="127.0.0.1")
    ap.add_argument("--build", metavar="PATH", help="Render the static site to PATH and exit.")
    args = ap.parse_args()

    if args.build:
        out = build_to(args.build)
        print(f"Apex Quant web app built → {out}", flush=True)
        return 0

    server = ThreadingHTTPServer((args.host, args.port), _Handler)
    url = f"http://{args.host}:{args.port}"
    print(f"Apex Quant web app → {url}   (Ctrl+C to stop)", flush=True)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nstopped.")
    finally:
        server.server_close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
